### ISSUE TITLE
NotSupportedException: audio property has been deprecated

### ISSUE THREAD

**Issue by TengkuFathullah** [MephestoKhaan/UnityEventVisualizer#10]
NotSupportedException: audio property has been deprecated
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.

Unity version : 2017.2.0f3

<img width="792" alt="screen shot 2018-08-09 at 2 28 20 pm" src="https://user-images.githubusercontent.com/17969112/43881965-8ee41e1c-9be0-11e8-8840-9c6c13c763f7.png">

**Comment by MephestoKhaan** [comment]
The code certainly does not call `.audio` anywhere so this is probably an error on a different place because some Monobehaviour is using the deprecated audio property?

A piece of the code using it (audio), or a screenshot of the Event linked would be very helpful for me to understand what is going on.

**Comment by TengkuFathullah** [comment]
Not sure how to show you my audio script event, since it quite long.

`public class PlayAudio : MonoBehaviour
{
	[System.Serializable]
	public class AudioEvent : UnityEvent<AudioClip, float>{}

    public bool Random;
	public bool GlobalBroadcast;

    [ShowIf("GlobalBroadcast")]
    public bool IgnoreGlobalCallback;
    [ShowIf("GlobalBroadcast")]
    public bool KillCallbackOnPlay;
    [ShowIf("GlobalBroadcast")]
	public string Channel;
    //TODO add audio delay if use pitch
	public AudioClip Clip;
	public AudioEvent OnTrigger;
    public UnityEvent OnStart;
    public UnityEvent OnComplete;

	CoroutineHandle currentCoroutine;
    AudioSource audioSource;
    PlayRandomAudio randomAudioScript;

    void Awake()
    {
        if (GlobalBroadcast == false)
        {
            if (GetComponent<AudioSource>() == null)
            {
                audioSource = gameObject.AddComponent<AudioSource>();
                StoryMain.Instance.OnStepChange += audioSource.Stop; // TODO: check this, might trigger even on not own respective scene
            }
            else
                audioSource = transform.GetComponent<AudioSource>();

            audioSource.playOnAwake = false;
            AudioMixer mixer = Resources.Load("Master") as AudioMixer;
            audioSource.outputAudioMixerGroup = mixer.FindMatchingGroups("SFX") [0];
        }

        if (Random)
            randomAudioScript = GetComponent<PlayRandomAudio>();
    }

	void Start()
	{
		if (GlobalBroadcast == false)
		{
            //GetComponentInParent<StoryStepMaster>().OnEnterSubscene += (int i) => audioSource.Stop();
		}
        else
        {
            audioSource = AudioMessenger_Receiver.GetAudioSource(Channel);
        }
	}

    public void PlayAudioAndStop(float time = 0)
    {
        if (GlobalBroadcast == false)
        {
            Internal_Play();

            if (Mathf.Approximately(time, 0) == false && time > 0)
                Timing.RunCoroutine(_DelayedCallback(time, audioSource.Stop), References.CoroutineTag.DelayedCallback);
        }
        else
        {
            Messenger.Broadcast<AudioClip, float>(Channel, Clip, time);
        }
    }

    public void PlayIfNotPlaying(float delay = 0)
    {
        // Check audio with delay is already running
        if (Timing.IsRunning(currentCoroutine))
            return;

        if (Random)
            Clip = randomAudioScript.GetRandomAudio();

        // Check audio is running
        if ((Clip == null && Random == false) || audioSource.isPlaying &&  audioSource.clip == Clip)
            return;

        audioSource.Stop();
        audioSource.clip = Clip;

        if (Mathf.Approximately(delay, 0))
        {
            Internal_Play();
        }
        else
            currentCoroutine = Timing.RunCoroutine(_DelayedPlay(delay), References.CoroutineTag.DelayedTrigger);
    }

    public void PlayOverride(float delay = 0)
    {
        if (Random)
            Clip = randomAudioScript.GetRandomAudio();
        
        if (Clip == null)
            return;

        audioSource.Stop();
        audioSource.clip = Clip;

        if (Mathf.Approximately(delay, 0))
        {
            Internal_Play();
        }
        else
            currentCoroutine = Timing.RunCoroutine(_DelayedPlay(delay), References.CoroutineTag.DelayedTrigger);
    }


    // Use for random play script
    public void PlayOverride(AudioClip clip)
    {
        if (clip == null)
            return;

        audioSource.Stop();
        audioSource.clip = clip;

        Internal_Play();
    }

    public void PlayWithPitch(float speedMultiplier = 0)
    {
        if (Clip == null)
            return;

        audioSource.Stop();
        audioSource.clip = Clip;
        audioSource.pitch = speedMultiplier;

        float newLength = Clip.length / speedMultiplier;

        // Local audio callback
        Timing.RunCoroutine(_CallbackHandler_Local(newLength), References.CoroutineTag.DelayedCallbackAudioLocal);

        // Global audio callback using channel
        if (IgnoreGlobalCallback == false)
            StoryMain.Instance.TriggerCallback(Channel, newLength);

        audioSource.Play();
    }

    void Internal_Play()
	{
        // Local audio callback
        Timing.RunCoroutine(_CallbackHandler_Local(Clip.length), References.CoroutineTag.DelayedCallbackAudioLocal);

        // Global audio callback using channel
        if (IgnoreGlobalCallback == false)
            StoryMain.Instance.TriggerCallback(Channel, Clip.length);

		audioSource.clip = Clip;

		audioSource.Stop();
		audioSource.Play();
	}

    IEnumerator<float> _DelayedCallback(float delay, System.Action callback)
    {
        yield return Timing.WaitForSeconds(delay);

        callback();
    }

	IEnumerator<float> _DelayedPlay(float delay)
	{
		yield return Timing.WaitForSeconds(delay);

        Internal_Play();
	}

    IEnumerator<float> _CallbackHandler_Local(float time)
    {
        OnStart.Invoke();
        yield return Timing.WaitForSeconds(time);
        OnComplete.Invoke();
    }

    public void KillDelayManually()
    {
        Timing.KillCoroutines(References.CoroutineTag.DelayedCallbackAudioLocal);
    }
}`

**Comment by kimsovan72** [comment]
FirstName: Kim
LastName: Sovan 
Gender: Male 
Birthday: 09/09/1985 
Email kimsovan72@gmail.com http://en.gravatar.com/kimsovan72.json Email Address: kimsovan72@gmail.com Email Hash: 9f6922687f291069820e61a49a8d7364 
List of Feder-ated IDs 
[FACEBOOK-115978649281593] 
List of Feder-ated IDs [Google:104336381654539103329]  
ACCOUNT GOOGLE CLOUD PLATFORM 
PROJECT NAME: KIM SOVAN 
PROJECT ID: KIM-SOVAN-1532076734377
PROJECT NUMBER: 846959491838 
Billng Management Console  aws-amazon  
Account ID:  716360388065 
Email: kimsovan72@gmail.com
https://console.aws.amazon.com/billing/home#/tax
Storage Google APIs #369562 
Account Google Ads 
Customer ID: 750-959-4564 
LinkedIn Customer Service Survey
Subject Line: Kim, please verify your new device Case #: 180715-000933 
https://linkedin.com/cambodia/in/kim-sovan-52756b164
Google Analytics 
Account : Kim Sovan (123356657)
Properties & app (UA-123356657-1) 
View: All website Data (179453459) 
Account Microsoft Additional Security 
Unique ID: 000340010D4036D3
Data Export User_147599_817376317_20180623122857.cvs (no-reply@orcid.uservoice.com) 

Granicus Case Created
Case #: 00253632
Case Status: New
Created on: 8/19/2018
(support@granicus.com) 

Re: HELP-1254 Re: [2-7885000022697] Re: EU-U.S. and Swiss-U.S. 
Privacy Shield Inquiries #212656816006887 
Reference #: 180616-000145
On Sunday, June 17, 2018, <SupportCenter@ieee.org>
<jira@us-sba.atlassian.net> 

The History Hub Admin 
Just click on the link below to validate your address and complete a short registration: 
https://historyhub.history.gov/validate.jspa?email=kimsovan72%40gmail.com&validationKey=f364a476bd45349fcd71889057d83a5ca9bcdede

If that link doesn't work, you can manually validate your email address by going to this link and entering the following information: 
https://historyhub.history.gov/validate!input.jspa

Email: kimsovan72@gmail.com 
Token: f364a476bd45349fcd71889057d83a5ca9bcdede (admin@historyhub.history.gov) 
Please review our Comment and Posting Policy and our Privacy Policy before posting.
If you didn't recently ask to join History Hub, please disregard this email. 

https://www.sparrho.com/p/new-pinboard/255875/

On Saturday, June 9, 2018, Washington Department of Revenue LISTSERV Server (16.0) <LISTSERV@listserv.dor.wa.gov>  
Command confirmation request (456AF8BB) 

Your IEEE Account has been created using the e-mail address kimsovan72@gmail.com.
An IEEE Account provides access to a variety of online services, depending on your membership and subscription status. Here are some of the things you can do with your IEEE Account:  
Account Member Number : 94997920

=== Add your details above here; please leave the following information intact === User: kimsovan72@gmail.com | Kim Sovan  Technology Vitality Index Report Request session 1150776 | <helpdesk@ip.com> 

If you need assistance, please do not reply to this email as it comes from an unmonitored address. Instead, please visit https://ip.com/contact and drop us a note from there.
Please click the following link: 
https://portal.ip.com/forgot-password.html?a=v&t=C61A2ABA1IEEFBFJD4J32W1AD&em=kimsovan72%40gmail.com
(no-reply@ip.com) 
If your email program does not allow you to click this link, point your web browser to: 
https://portal.ip.com/forgot-password.html?a=v
The screen you receive will prompt you for your email and your "ticket" number.
For your ticket number, enter: (C61A2ABA1IEEFBFJD4J32W1AD) 
New Comment added to Request #27057 "IP.com - Contact Us Form Submission" in project Support  | <security@ip.com> <ckneuer@ip.com> 

Foresee Account Support 
Request #00037380 Confirmed: Re: The World Bank Survey - give us your opinion - ref:_00D46tfr._500466cqsk:ref
(supportreply@foresee.com)  

https://my.smartrecruiters.com/api/profile/json-export 
Phnom Penh Cambodia
