### ISSUE TITLE
Unity Editor crashed on Events Graph Editor opening

### ISSUE THREAD

**Issue by Pimeko** [MephestoKhaan/UnityEventVisualizer#12]
Hi,

Whenever I try to open the Events Graph Editor, the Unity Editor crashes.
Version used: 2019.2.0f1

Thanks

**Comment by MephestoKhaan** [comment]
Thanks for pointing this out.

I just downloaded 2019.2.4 and could not see anything major. But some small nullchecks here and there, it does not crash my editor so try the latest release with those fixes: 
https://github.com/MephestoKhaan/UnityEventVisualizer/releases/tag/1.3.1
and let me know if it is still happening, maybe you can give me a bit more of information about your project or attach the Log from the unity folder?

**Comment by Pimeko** [comment]
Thank you for your quick answer!

I managed to target what was causing the crash, and it is with generic type constraints. Here are two dummy scripts that can make the Editor crash when opening the Events Graph Editor.

**Test.cs**
```c#
using UnityEngine;
using UnityEngine.Events;

public abstract class Test<T_UNITY_EVENT> : MonoBehaviour
    where T_UNITY_EVENT : UnityEvent<int>
{
    public T_UNITY_EVENT callback;
}
```

**TestInt.cs**
```c#
using UnityEngine.Events;

public class TestInt : Test<UnityEvent<int>>
{
}
```

**Comment by MephestoKhaan** [comment]
Awesome thank you so much.
I am super busy at the moment but will try to find a fix as soon as
possible.

**Comment by MephestoKhaan** [comment]
Ages later finally starting to dig into this.

The Unity.Log throws some light here:
`compute_class_bitmap: Invalid type 13 for field Test`1[T_UNITY_EVENT]:Zcallback` that is the last message before crashing silently.

**Comment by MephestoKhaan** [comment]
Check the latest release, I hope it all works
