### ISSUE TITLE
Graph Editor cannot be dragged.

### ISSUE THREAD

**Issue by BelieveXiaoShuai** [MephestoKhaan/UnityEventVisualizer#13]
Enviroment: Unity 2019.2.1f1
Question: When there are many objects in UnityEvent, I want to drag to see the event notification channel, but I can't do it.

**Comment by MephestoKhaan** [comment]
Hi!
You should be able to drag the window using the Middle Mouse Button. I tested in 2017 and 2019.4 as well and never seen this not working.

https://i.gyazo.com/43b4dcd1a8ce5948fb82050b90034d55.mp4

**Comment by BelieveXiaoShuai** [comment]
Thank you! I just know how to use this.
