### ISSUE TITLE
Is there any plan to put this tool into the Unity Package?

### ISSUE THREAD

**Issue by BelieveXiaoShuai** [MephestoKhaan/UnityEventVisualizer#14]
This tool is very good and easy to use. If it can be put into Package, it can be updated easily and will not be mixed with Assets project.

**Comment by MephestoKhaan** [comment]
Thanks!

I agree yes, I am looking into that, at the moment talking with the Unity Asset Store to release it there for free, will see if I can release it later as a package for easier use :)

**Comment by BelieveXiaoShuai** [comment]
I really look forward to it.

**Comment by BelieveXiaoShuai** [comment]
If this tool can be placed in the Package Manager in the Unity editor instead of the Asset Store, it may be better and the update iteration can be more free and frequent.
