### ISSUE TITLE
When there are many objects in the scene, the Graph Editor runs very slow, which is difficult to operate.

### ISSUE THREAD

**Issue by BelieveXiaoShuai** [MephestoKhaan/UnityEventVisualizer#15]

**Comment by MephestoKhaan** [comment]
Roughly, how many do you have? So I can test possible optimizations

**Comment by BelieveXiaoShuai** [comment]
Let me count the number of objects.Just now I opened the Graph Editor and then clicked to open my scene.
![image](https://user-images.githubusercontent.com/26036057/75453917-960ffb00-59af-11ea-82f6-35afacaaba62.png)

**Comment by MephestoKhaan** [comment]
Just an estimate is good enough!

**Comment by BelieveXiaoShuai** [comment]
28404 active gameobjects

**Comment by MephestoKhaan** [comment]
Wow ok, that is quite a lot. 
I will see what I can do but can't guarantee it will work (my PC cannot even support those many gameobjects in the normal editor).

If you don't need visualizing the Event being triggered maybe there is a quick win for you in disabling that in code?

**Comment by BelieveXiaoShuai** [comment]
Deactivating unwanted objects will indeed reduce many triggers, but if I don't know which objects will be triggered, I may not be able to achieve my goal if I deactivate them rashly.

**Comment by MephestoKhaan** [comment]
Well, running this on VRTK 4 demo surely brings a LOT of gameobjects:
![image](https://user-images.githubusercontent.com/4976810/78580056-256fc000-7832-11ea-949e-899600fcb698.png)

Going to add a button so you can just show the graph of all events under selected gameobjets so you don;t need to fully open it

**Comment by MephestoKhaan** [comment]
Check release 1.4

**Comment by BelieveXiaoShuai** [comment]
Thank U!
