### ISSUE TITLE
Error when trying to add via Git url.

### ISSUE THREAD

**Issue by MostHated** [MephestoKhaan/UnityEventVisualizer#21]
Hey there,
    I tried to add the package via Git url but received the following error:

```
Cannot perform upm operation: Unable to add package [https://github.com/MephestoKhaan/UnityEventVisualizer.git]:
  [https://github.com/MephestoKhaan/UnityEventVisualizer.git] does not point to a valid package repository. No package manifest was found. Verify the repository URL and make sure the package is located in the root folder of the repository. [NotFound].See console for more details
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

Just wanted to make sure you were aware
Thanks,
-MH

**Comment by MephestoKhaan** [comment]
Well... months later I finally got back to this.

The repo now should be working as a .git. 

But for some reason the Samples are coming out empty, even though they work as a embedded package. Asking about it here: https://forum.unity.com/threads/empty-samples.998878/

**Comment by MephestoKhaan** [comment]
Fixed!
