### ISSUE TITLE
Integration in SDD EventManager

### ISSUE THREAD

**Issue by monsdar** [MephestoKhaan/UnityEventVisualizer#7]
Just wanted to let you know that I was able to integrate this EventVisualizer with the [SDD EventManager](https://github.com/UbimaxFrontline/EventManager).

Awesome work, just a few code changes were needed and most features are still usable.

**Comment by MephestoKhaan** [comment]
Awesome! :-) Thanks for letting me know.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
