### ISSUE TITLE
EventsGraphGUI does not compile.

### ISSUE THREAD

**Issue by arctop-sk** [MephestoKhaan/UnityEventVisualizer#8]
Hi. I just downloaded the latest release package, and there is a compile error.

in EventsGraphGUI.cs , line 50, there is a call to DragSelection(new Rect(-5000, -5000, 10000, 10000));

but DragSelection() has no parameters in the method signature. 
For now I resolved it by removing the parameter, but wanted to raise the issue, and I was also wondering what was the purpose of the Rect, and if it will still work as expected.

**Comment by MephestoKhaan** [comment]
Hey thanks!

Yes you are Completely right. That is a difference between 5.6 and newer
versions. You can safely comment it out and I should add a fix for newer
versions. (or feel free to do a pull request)


It is a bit of a weird one. Because one year ago unity said they are not
disclosing the Graph API because they are not working on it.....  And then
they released 2017 and got that error that proves they are contradicting
themselves!

**Comment by arctop-sk** [comment]
Ok. Thank, I didn't actually dig enough to even notice this is Unity's class. 

Found this though : https://docs.unity3d.com/2018.1/Documentation/ScriptReference/Experimental.UIElements.GraphView.GraphView.html

So looks like it is in development at some capacity.

I'm wondering, did you ever get zooming to work on the graph? I see a EditorZoomArea class but it doesn't seem to be referenced anywhere. Also, I see that there is a private zoomLevel field/property in the Unity class, but alas, it is private. I'm wondering how to get it working, that would really improve the usability of this tool

**Comment by arctop-sk** [comment]
Yeah. I'll probably get a chance to investigate it at work next week. I know that the Animator window is now zoomable, so the solution is probably implemented there, just need to find exactly where and implement it.

for the original issue, I only downloaded the package right now, so I don't have a clone for a pull request.

**Comment by MephestoKhaan** [comment]
Seems that the zooming was added (and the whole class renamed from the internal GraphUI to this GraphView) in Unity 2018, so I am not sure if I want to break compatibility with 5.6 or 2017 *yet*.

I am going to keep looking at the much needed zoom (that GraphView has but GraphUI doesnt.  On the mean time I will push the simple fix for compiling in Unity 2017 or newer

**Comment by arctop-sk** [comment]
Cheers.

I've decompiled and looked at the AnimatorWindow inside UnityEditor.Graphs dll. Zoom is supported there (it is AnimatorWindowTool iirc) and does work  in 2017 (which is the version i'm on), but will require some major refactoring to get working with the current implementation, probably almost a complete re-write.

**Comment by MephestoKhaan** [comment]
Thanks will look into it!
GraphUI does contain a method `public void ZoomToGraph(Graph g);`  but when
calling it it returns a NotImplemented exception  ):

**Comment by MephestoKhaan** [comment]
Goddamnit, the matrix solution does have a lot of problems 👎 
https://i.gyazo.com/90545e327de6a5d9170046133dae15d7.mp4

**Comment by MephestoKhaan** [comment]
Some progress tho! Now If i manage to allign those edges... https://i.gyazo.com/156ca20417d9c4b781d16f472bdeab4e.mp4

**Comment by MephestoKhaan** [comment]
A bit hackyt and still a lot of improvement could be done but at least it does zoom correctly!
https://gyazo.com/a019dda57bf115517bd2b36e700001dd

pushing now
